run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
    - unparam
    - funlen
    - lll
    - gocritic
    - copyloopvar
  disable:
    - exportloopref   # Deprecated in Go 1.22+

linters-settings:
  gocyclo:
    min-complexity: 15
  
  funlen:
    lines: 60
    statements: 40
  
  lll:
    line-length: 120
  
  govet:
    disable:
      - fieldalignment  # Already disabled above, but double-check
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - rangeValCopy  # We fixed this already, but keep disabled if needed

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude specific patterns that are not critical
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - errcheck
        - revive
        - gocritic
    
    # Allow field alignment issues (minor optimization)
    - linters:
        - govet
      text: "fieldalignment:"
    
    # Exclude color output function error checking (not critical)
    - linters:
        - errcheck
      text: "Error return value of.*Color.*is not checked"
    
    # Exclude print function error checking (not critical for output)
    - linters:
        - errcheck
      text: "Error return value of.*Print.*is not checked"
    
    # Allow unnamed results for simple utility functions
    - linters:
        - gocritic
      text: "unnamedResult:"
    
    # Allow old octal literals in tests
    - path: _test\.go
      linters:
        - gocritic
      text: "octalLiteral:"
    
    # Allow variable naming in tests
    - path: _test\.go
      linters:
        - revive
      text: "var-naming:"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true